modules/admin/controllers/EpisodeController.php
<?php

namespace app\modules\admin\controllers;

use Yii;
use app\modules\admin\models\Episode;
use app\modules\admin\models\EpisodeSearch;
use app\modules\admin\models\Series;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;


/**
 * EpisodeController implements the CRUD actions for Episode model.
 */
class EpisodeController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Episode models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new EpisodeSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Episode model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($slug)
    {
        return $this->render('view', [
            'model' => $this->findModelBySlug($slug),
        ]);
    }

    /**
     * Creates a new Episode model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Episode();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {   
                    
            Yii::$app->session->setFlash('success', "Episode <strong>$model->title</strong> was created succesfully.");
            return $this->redirect(['episode/index']);
        }

        return $this->render('create', [
            'model' => $model,
            'series' => yii\helpers\ArrayHelper::map(Series::find()->all(),'id','title')
        ]);
    }

    /**
     * Updates an existing Episode model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($slug)
    {
        $model = $this->findModelBySlug($slug);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('success', "Episode <strong>$model->title</strong> was updated succesfully.");
            return $this->redirect(['view', 'slug' => $model->slug]);
        }

        return $this->render('update', [
            'model' => $model,
            'series' => yii\helpers\ArrayHelper::map(Series::find()->all(),'id','title')
        ]);
    }

    /**
     * Deletes an existing Episode model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($slug)
    {
        $model = $this->findModelBySlug($slug);
        $model->delete();
        
        Yii::$app->session->setFlash('success', "Episode <strong>$model->title</strong> was deleted succesfully.");
        
        return $this->redirect(['index']);
    }

    /**
     * Finds the Episode model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Episode the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Episode::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
    
    /**
     * Finds the Episode model based on the slug.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $slug
     * @return Episode the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModelBySlug($slug)
    {
        if (($model = Episode::findOne(['slug' => $slug])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

modules/admin/controllers/MovieController.php
<?php

namespace app\modules\admin\controllers;

use Yii;
use app\modules\admin\models\Movie;
use app\modules\admin\models\MovieSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use dektrium\user\filters\AccessRule;

/**
 * MovieController implements the CRUD actions for Movie model.
 */
class MovieController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'ruleConfig' => [
                    'class' => AccessRule::className(),
                ],
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['admin'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Movie models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new MovieSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Movie model.
     * @param integer $slug
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($slug)
    {
        return $this->render('view', [
            'model' => $this->findModelBySlug($slug),
        ]);
    }

    /**
     * Creates a new Movie model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Movie();
        
        if ($model->load(Yii::$app->request->post()) && $model->save()) {                        
            Yii::$app->session->setFlash('success', "Movie <strong>$model->title</strong> was created succesfully.");
            return $this->redirect(['movie/index']);    
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }   
    
    /**
     * Updates an existing Movie model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $slug
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($slug)
    {
        $model = $this->findModelBySlug($slug);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('success', "Movie <strong>$model->title</strong> was updated succesfully.");
            return $this->redirect(['view', 'slug' => $model->slug]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Movie model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $slug
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($slug)
    {
        $model = $this->findModelBySlug($slug);
        $model->delete();   
        
        Yii::$app->session->setFlash('success', "Movie <strong>$model->title</strong> was deleted succesfully.");
        
        return $this->redirect(['index']);
    }

    /**
     * Finds the Movie model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Movie the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Movie::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
    
    /**
     * Finds the Movie model based on the slug.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $slug
     * @return Episode the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModelBySlug($slug)
    {
        if (($model = Movie::findOne(['slug' => $slug])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

modules/admin/controllers/SeriesController.php
<?php

namespace app\modules\admin\controllers;

use Yii;
use app\modules\admin\models\Series;
use app\modules\admin\models\SeriesSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;


/**
 * SeriesController implements the CRUD actions for Series model.
 */
class SeriesController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Series models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new SeriesSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Series model.
     * @param integer $slug
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($slug)
    {
        return $this->render('view', [
            'model' => $this->findModelBySlug($slug),
        ]);
    }

    /**
     * Creates a new Series model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Series();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('success', "Series <strong>$model->title</strong> was created succesfully.");
            return $this->redirect(['series/index']);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Series model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $slug
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($slug)
    {
        $model = $this->findModelBySlug($slug);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('success', "Series <strong>$model->title</strong> was updated succesfully.");
            return $this->redirect(['view', 'slug' => $model->slug]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Series model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $slug
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($slug)
    {
        $model = $this->findModelBySlug($slug);
        $model->delete();
        
        Yii::$app->session->setFlash('success', "Series <strong>$model->title</strong> was deleted succesfully.");
        
        return $this->redirect(['index']);
    }

    /**
     * Finds the Series model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Series the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Series::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
    
    /**
     * Finds the Series model based on the slug.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $slug
     * @return Episode the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModelBySlug($slug)
    {
        if (($model = Series::findOne(['slug' => $slug])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
}

modules/admin/views/admin/dashboard.php
<?php
use yii\helpers\Url;

/* @var $this yii\web\View */

$this->title = 'Dashboard';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="row">
    <div class="col-md-12">
        <div class="col-md-4 col-xs-6">
            <div class="info-box">
                <!-- Apply any bg-* class to to the icon to color it -->
                <span class="info-box-icon bg-red"><i class="fa fa-eye"></i></span>
                <div class="info-box-content">
                    <span class="info-box-text">Views</span>
                    <span class="info-box-number"><?=$views?></span>
                </div><!-- /.info-box-content -->
            </div><!-- /.info-box -->
        </div>
        <div class="col-md-4 col-xs-6">
            <div class="info-box">
                <!-- Apply any bg-* class to to the icon to color it -->
                <span class="info-box-icon bg-red"><i class="fa fa-users"></i></span>
                <div class="info-box-content">
                    <span class="info-box-text">Users</span>
                    <span class="info-box-number"><?=$users?></span>
                </div><!-- /.info-box-content -->
            </div><!-- /.info-box -->
        </div>
        <div class="col-md-4 col-xs-6">
            <div class="info-box">
                <span class="info-box-icon bg-red"><i class="fa fa-files-o"></i></span>

                <div class="info-box-content">
                    <span class="info-box-text">Movies</span>
                    <span class="info-box-number"><?=$movies?></span>
                </div>
                <!-- /.info-box-content -->
            </div>
        </div>
        <div class="col-md-4 col-xs-6">
            <div class="info-box">
                <span class="info-box-icon bg-red"><i class="fa fa-files-o"></i></span>

                <div class="info-box-content">
                    <span class="info-box-text">Series</span>
                    <span class="info-box-number"><?=$series?></span>
                </div>
                <!-- /.info-box-content -->
            </div>
        </div>
        <div class="col-md-4 col-xs-6">
            <div class="info-box">
                <span class="info-box-icon bg-red"><i class="fa fa-files-o"></i></span>

                <div class="info-box-content">
                    <span class="info-box-text">Seasons</span>
                    <span class="info-box-number"><?=$seasons?></span>
                </div>
                <!-- /.info-box-content -->
            </div>
        </div>
        <div class="col-md-4 col-xs-6">
            <div class="info-box">
                <span class="info-box-icon bg-red"><i class="fa fa-files-o"></i></span>

                <div class="info-box-content">
                    <span class="info-box-text">Episodes</span>
                    <span class="info-box-number"><?=$episodes?></span>
                </div>
                <!-- /.info-box-content -->
            </div>
        </div>
    </div>
    <div class="col-md-12">
        <div class="box box-danger">
            <div class="box-header with-border">
                <h3 class="box-title">Latest Members</h3>

                <div class="box-tools pull-right">
                    <span class="label label-danger">8 New Members</span>
                    <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i>
                    </button>
                </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body no-padding">
                <ul class="users-list clearfix">
                    <?php foreach($newMembers as $newMember): ?>
                    <li>
        <!--                <img src="dist/img/user1-128x128.jpg" alt="User Image">-->
                        <a class="users-list-name" href="#"><?=$newMember->username?></a>
                        <span class="users-list-date"><?=\Yii::$app->formatter->asDate($newMember->created_at, 'full')?></span>
                    </li>
                    <?php endforeach; ?>
                    <?php foreach($newMembers as $newMember): ?>
                    <li>
        <!--                <img src="dist/img/user1-128x128.jpg" alt="User Image">-->
                        <a class="users-list-name" href="#"><?=$newMember->username?></a>
                        <span class="users-list-date"><?=\Yii::$app->formatter->asDate($newMember->created_at, 'full')?></span>
                    </li>
                    <?php endforeach; ?>
                </ul>
                <!-- /.users-list -->
            </div>
            <!-- /.box-body -->
            <div class="box-footer text-center">
                <a href="<?=Url::to('/user/admin/index')?>" class="uppercase">View All Users</a>
            </div>
            <!-- /.box-footer -->
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-4">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Recent Movies</h3>

                <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <ul class="products-list product-list-in-box">
                    <?php foreach($recentMovies as $item): ?> 
                    <li class="item">
                        <div class="product-img">
                            <img src="<?=$item->getImgSrc('small_banner')?>" alt="<?=$item->title?>">
                        </div>
                        <div class="product-info">
                            <a href="<?=Url::to(['movie/view', 'slug' => $item->slug])?>" class="product-title"><?=$item->title?>
                                <span class="label label-info pull-right">movies</span></a>
                            <span class="product-description">
                                <?=$item->brief?>
                            </span>
                        </div>
                    </li>
                    <?php endforeach; ?>
                    <!-- /.item -->
                </ul>
            </div>
            <!-- /.box-body -->
        <!--    <div class="box-footer text-center">
                <a href="javascript:void(0)" class="uppercase">View All Products</a>
            </div>-->
            <!-- /.box-footer -->
        </div>
    </div>
    <div class="col-md-4">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Recent Episodes</h3>

                <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <ul class="products-list product-list-in-box">
                    <?php foreach($recentEpisodes as $item): ?> 
                    <li class="item">
                        <div class="product-img">
                            <img src="<?=$item->getImgSrc('small_banner')?>" alt="<?=$item->title?>">
                        </div>
                        <div class="product-info">
                            <a href="<?=Url::to(['episode/view', 'slug' => $item->slug])?>" class="product-title"><?=$item->title?>
                                <span class="label label-warning pull-right">episodes</span></a>
                            <span class="product-description">
                                <?=$item->brief?>
                            </span>
                        </div>
                    </li>
                    <?php endforeach; ?>
                    <!-- /.item -->
                </ul>
            </div>
            <!-- /.box-body -->
        <!--    <div class="box-footer text-center">
                <a href="javascript:void(0)" class="uppercase">View All Products</a>
            </div>-->
            <!-- /.box-footer -->
        </div>
    </div>
    <div class="col-md-4">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Recent Series</h3>

                <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <ul class="products-list product-list-in-box">
                    <?php foreach($recentSeries as $item): ?> 
                    <li class="item">
                        <div class="product-img">
                            <img src="<?=$item->getImgSrc('small_banner')?>" alt="<?=$item->title?>">
                        </div>
                        <div class="product-info">
                            <a href="<?=Url::to(['series/view', 'slug' => $item->slug])?>" class="product-title"><?=$item->title?>
                                <span class="label label-danger pull-right">series</span></a>
                            <span class="product-description">
                                <?=$item->brief?>
                            </span>
                        </div>
                    </li>
                    <?php endforeach; ?>
                    <!-- /.item -->
                </ul>
            </div>
            <!-- /.box-body -->
        <!--    <div class="box-footer text-center">
                <a href="javascript:void(0)" class="uppercase">View All Products</a>
            </div>-->
            <!-- /.box-footer -->
        </div>
    </div>
</div>